"""add products table and allocation_plan column

Revision ID: 1a1e21404804
Revises: a75a9f3fea0d
Create Date: 2026-05-20 18:52:56.418125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a1e21404804'
down_revision: Union[str, Sequence[str], None] = 'a75a9f3fea0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('allocation_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'allocation_plan')
    # ### end Alembic commands ###
